### ISSUE TITLE
Remove yarn-error.log

### ISSUE THREAD

**Issue by lsmoura** [SnekNOTSnake/react-typescript-boilerplate#1]
Remove yarn-error.log from the repository and add it to `.gitignore`.

It adds no value to the repository or the code, exposes some local stuff from the user's machine to the world (like your home folder, os, etc), and may be big.

**Comment by SnekNOTSnake** [comment]
Ahh right, I forgot to do that. Thanks for mentioning it.
BTW this is my first GitHub issue. Heck Yeah!
